inputs:
  flag_arm:
    default: false
    type: boolean
  
runs:
  using: composite
  steps:
  - uses: ref_action/.github/actions/universal/action_check_installs
    with: 
      flag_arm: ${{inputs.flag_arm}}