inputs:
  flag_arm:
    default: false
    type: boolean
  
runs:
  steps:
  - name: Checkout actions repo for wanted branch
    uses: actions/checkout@v4
    with: 
      repository: ${{inputs.workingOrg}}/${{inputs.workingRepo}}
      ref: ${{inputs.workingBranch}}
      sparse-checkout: .github/actions/universal/action_check_installs/action.yml
      sparse-checkout-cone-mode: true
  - name: test checkout
    shell: bash
    run: |
      ls
      cd .github
      ls
      cd actions
      ls
      cd universal
      ls
      cd action_check_installs
      ls
      echo ${{github.action_path}}