inputs:
  arm_path:
    type: string
  arm_tar_path:
    type: string
  arm_dir_path:
    type: string
  flag_arm:
    default: false
    type: boolean
  

runs:
  using: composite
  steps: 
  - name: Install bleeding-edge-toolchain
    shell: bash
    working-directory: /tmp
    run: |
      wget --progress=dot:giga https://distortos.org/files/ci/arm-none-eabi-gcc-${{matrix.toolchain}}.tar.xz
      tar -xf arm-none-eabi-gcc-${{matrix.toolchain}}.tar.xz
      echo "$(cd arm-none-eabi-gcc-${{matrix.toolchain}}/bin && pwd)" >> $GITHUB_PATH
  - if: ${{inputs.flag_arm}} && false
    uses: MertensFlo/StateOS_BA/.github/actions/universal/action_build_specific_commands@Testing_workflows
    with:
      flag_arm: ${{inputs.flag_arm}}
      arm_path: ${{inputs.arm_path}}
      arm_tar_path: ${{inputs.arm_tar_path}}
      arm_dir_path: ${{inputs.arm_dir_path}}
