inputs:
  arm_path:
    type: string
  arm_tar_path:
    type: string
  arm_dir_path:
    type: string
  arm_condition:
    type: string
  flag_arm:
    default: false
    type: boolean
  toolchain:
    default: 14.1.0-240616
    type: string
  

runs:
  using: composite
  steps: 
  - run: echo ${{inputs.arm_path}}
    shell: bash
  - if: false
    name: Install bleeding-edge-toolchain
    shell: bash
    working-directory: /tmp
    run: |
      wget --progress=dot:giga https://distortos.org/files/ci/arm-none-eabi-gcc-${{inputs.toolchain}}.tar.xz
      tar -xf arm-none-eabi-gcc-${{inputs.toolchain}}.tar.xz
      echo "$(cd arm-none-eabi-gcc-${{inputs.toolchain}}/bin && pwd)" >> $GITHUB_PATH
  - if: ${{inputs.flag_arm}}
    uses: MertensFlo/StateOS_BA/.github/actions/universal/action_build_specific_commands@Testing_workflows
    with:
      flag_arm: ${{inputs.flag_arm}}
      arm_path: ${{inputs.arm_path}}
      arm_tar_path: ${{inputs.arm_tar_path}}
      arm_dir_path: ${{inputs.arm_dir_path}}
      arm_condition: ${{inputs.arm_condition}}
