#
# file: build-test.yml
#
# author: Copyright (C) 2021-2024 Kamil Szczygiel https://distortec.com https://freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

name: Build Test

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - 14.1.0-240616
    steps:
    - uses: actions/checkout@v4
    - name: Install bleeding-edge-toolchain
      shell: bash
      working-directory: /tmp
      run: |
        wget --progress=dot:giga https://distortos.org/files/ci/arm-none-eabi-gcc-${{matrix.toolchain}}.tar.xz
        tar -xf arm-none-eabi-gcc-${{matrix.toolchain}}.tar.xz
        echo "$(cd arm-none-eabi-gcc-${{matrix.toolchain}}/bin && pwd)" >> $GITHUB_PATH
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install ninja-build
    - name: Build
      shell: bash
      run: ./scripts/buildAllConfigurations.sh configurations distortosTest
      