#
# file: build-test.yml
#
# author: Copyright (C) 2021-2024 Kamil Szczygiel https://distortec.com https://freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

name: Build Test

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  call-generic_pipeline:
    uses: MertensFlo/StateOS_BA/.github/workflows/pipeline.yml@Testing_workflows
    with:
      buildSystem: ubuntu-latest
      workingBranch: Testing_workflows
      workingRepo: StateOS_BA 
      workingOrg: MertensFlo
      callerBranch: dev_github
      callerRepo: DISTORTOS_BA
      callerOrg: MertensFlo
      arm_condition: --progress=dot:giga
      arm_path: https://distortos.org/files/ci/arm-none-eabi-gcc-14.1.0-240616.tar.xz
      arm_tar_path: ARM_TAR_PATH=arm-none-eabi-gcc-14.1.0-240616.tar.xz
      arm_dir_path: "$(cd arm-none-eabi-gcc-14.1.0-240616/bin && pwd)"
      cmake_version: cmake
      flag_arm: true
      flag_submodule: false
      flag_ninja: true
      example_test: false
      static_test: false
      unit_test: false
